//
//  AppCopy.swift
//  Anky
//

import Foundation

enum AppCopyKey: String {
    case welcomeIntroBody
    case welcomeBiometryBody
    case welcomeKeychainBody 
    case welcomeNotificationsBody
    case welcomeContinueAction
    case welcomeEnableBiometryAction
    case welcomeEnableNotificationsAction
    case welcomeStepLabel
    case restorePhraseAction
    case restoreTitle
    case restoreBody
    case restorePlaceholder
    case restoreConfirmAction
    case restoreCancelAction
    case storiesTab
    case writeTab
    case youTab
    case persistedAnkysTitle
    case noPersistedAnkysTitle
    case noPersistedAnkysBody
    case pendingSyncTitle
    case pendingSyncBody
    case seedIdentityTitle
    case walletLabel
    case keychainStatusLabel
    case localIdentityLabel
    case securedValue
    case pendingValue
    case rebootIdentityAction
    case rebootIdentityBody
    case identityReadyValue
    case identityMissingValue
    case openAnkysAction
    case unlockTitle
    case unlockBody
    case unlockAction
}

struct AppCopy {
    private static let fallbackLanguageCode = "en"

    static var current: AppCopy {
        AppCopy(languageCode: resolvedLanguageCode())
    }

    let languageCode: String

    subscript(key: AppCopyKey) -> String {
        if let translation = Self.translations[languageCode]?[key] {
            return translation
        }

        return Self.translations[Self.fallbackLanguageCode]?[key] ?? key.rawValue
    }

    private static func resolvedLanguageCode() -> String {
        let preferred = Locale.preferredLanguages.first ?? fallbackLanguageCode
        let normalized = preferred.replacingOccurrences(of: "_", with: "-")
        return normalized.split(separator: "-").first.map(String.init) ?? fallbackLanguageCode
    }

    private static let translations: [String: [AppCopyKey: String]] = [
        "en": [
            .welcomeIntroBody: "Everything that you will do here is an excuse for you to write 8 minutes.",
            .welcomeBiometryBody: "Activate Face ID to keep your secrets intact.",
            .welcomeKeychainBody: "Save your seed phrase to iCloud Keychain. Apple keeps it protected for you.",
            .welcomeNotificationsBody: "Activate notifications. Every day at 6 AM, Anky will ask: how are you?",
            .welcomeContinueAction: "Continue",
            .welcomeEnableBiometryAction: "Activate Face ID",
            .welcomeEnableNotificationsAction: "Activate notifications",
            .welcomeStepLabel: "Step",
            .restorePhraseAction: "Restore phrase",
            .restoreTitle: "Restore with 24 words",
            .restoreBody: "Enter the phrase locally. Anky never sends it anywhere.",
            .restorePlaceholder: "24 words",
            .restoreConfirmAction: "Restore",
            .restoreCancelAction: "Back",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "You",
            .persistedAnkysTitle: "Persisted ankys",
            .noPersistedAnkysTitle: "Nothing persisted yet",
            .noPersistedAnkysBody: "A real anky will appear here after it persists.",
            .pendingSyncTitle: "Waiting to persist",
            .pendingSyncBody: "This real anky is still local. It unlocks only after the backend persists it.",
            .seedIdentityTitle: "Seed identity",
            .walletLabel: "Wallet",
            .keychainStatusLabel: "Keychain",
            .localIdentityLabel: "Identity",
            .securedValue: "Secured",
            .pendingValue: "Pending",
            .rebootIdentityAction: "Reboot identity",
            .rebootIdentityBody: "Delete the local key, local drafts, and begin again with a new phrase.",
            .identityReadyValue: "Ready",
            .identityMissingValue: "Missing",
            .openAnkysAction: "Open ankys",
            .unlockTitle: "Locked",
            .unlockBody: "Face ID keeps your writing private when you come back.",
            .unlockAction: "Unlock",
        ],
        "es": [
            .welcomeIntroBody: "Todo lo que haras aqui es una excusa para escribir 8 minutos.",
            .welcomeBiometryBody: "Activa Face ID para mantener tus secretos intactos.",
            .welcomeKeychainBody: "Guarda tu frase semilla en iCloud Keychain. Apple la protege por ti.",
            .welcomeNotificationsBody: "Activa las notificaciones. Cada dia a las 6 AM, Anky te preguntara: como estas?",
            .welcomeContinueAction: "Continuar",
            .welcomeEnableBiometryAction: "Activar Face ID",
            .welcomeEnableNotificationsAction: "Activar notificaciones",
            .welcomeStepLabel: "Paso",
            .keychainStatusLabel: "Llavero",
            .securedValue: "Protegido",
            .pendingValue: "Pendiente",
            .unlockTitle: "Bloqueado",
            .unlockBody: "Face ID mantiene tu escritura privada cuando vuelves.",
            .unlockAction: "Desbloquear",
            .restorePhraseAction: "Restaurar frase",
            .restoreTitle: "Restaurar con 24 palabras",
            .restoreBody: "Ingresa la frase localmente. Anky nunca la envia.",
            .restorePlaceholder: "24 palabras",
            .restoreConfirmAction: "Restaurar",
            .restoreCancelAction: "Volver",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "Tu",
        ],
        "pt": [
            .welcomeIntroBody: "Tudo o que voce vai fazer aqui e uma desculpa para escrever por 8 minutos.",
            .welcomeBiometryBody: "Ative o Face ID para manter seus segredos intactos.",
            .welcomeKeychainBody: "Salve sua frase-semente no iCloud Keychain. A Apple a protege para voce.",
            .welcomeNotificationsBody: "Ative as notificacoes. Todos os dias as 6 AM, a Anky vai perguntar: como voce esta?",
            .welcomeContinueAction: "Continuar",
            .welcomeEnableBiometryAction: "Ativar Face ID",
            .welcomeEnableNotificationsAction: "Ativar notificacoes",
            .welcomeStepLabel: "Passo",
            .keychainStatusLabel: "Chaves",
            .securedValue: "Protegido",
            .pendingValue: "Pendente",
            .unlockTitle: "Bloqueado",
            .unlockBody: "O Face ID mantem sua escrita privada quando voce volta.",
            .unlockAction: "Desbloquear",
            .restorePhraseAction: "Restaurar frase",
            .restoreTitle: "Restaurar com 24 palavras",
            .restoreBody: "Digite a frase localmente. A Anky nunca a envia.",
            .restorePlaceholder: "24 palavras",
            .restoreConfirmAction: "Restaurar",
            .restoreCancelAction: "Voltar",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "Tu",
        ],
        "fr": [
            .welcomeIntroBody: "Tout ce que vous ferez ici est une excuse pour ecrire pendant 8 minutes.",
            .welcomeBiometryBody: "Activez Face ID pour garder vos secrets intacts.",
            .welcomeKeychainBody: "Enregistrez votre phrase de recuperation dans iCloud Keychain. Apple la protege pour vous.",
            .welcomeNotificationsBody: "Activez les notifications. Chaque jour a 6 h, Anky demandera : comment allez-vous ?",
            .welcomeContinueAction: "Continuer",
            .welcomeEnableBiometryAction: "Activer Face ID",
            .welcomeEnableNotificationsAction: "Activer les notifications",
            .welcomeStepLabel: "Etape",
            .keychainStatusLabel: "Trousseau",
            .securedValue: "Protege",
            .pendingValue: "En attente",
            .unlockTitle: "Verrouille",
            .unlockBody: "Face ID garde votre ecriture privee quand vous revenez.",
            .unlockAction: "Deverrouiller",
            .restorePhraseAction: "Restaurer la phrase",
            .restoreTitle: "Restaurer avec 24 mots",
            .restoreBody: "Entrez la phrase localement. Anky ne l'envoie jamais.",
            .restorePlaceholder: "24 mots",
            .restoreConfirmAction: "Restaurer",
            .restoreCancelAction: "Retour",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "Toi",
        ],
        "de": [
            .welcomeIntroBody: "Alles, was du hier tust, ist ein Vorwand, 8 Minuten zu schreiben.",
            .welcomeBiometryBody: "Aktiviere Face ID, damit deine Geheimnisse intakt bleiben.",
            .welcomeKeychainBody: "Speichere deine Seed-Phrase im iCloud-Schlusselbund. Apple schutzt sie fur dich.",
            .welcomeNotificationsBody: "Aktiviere Mitteilungen. Jeden Tag um 6 Uhr fragt Anky: wie geht es dir?",
            .welcomeContinueAction: "Weiter",
            .welcomeEnableBiometryAction: "Face ID aktivieren",
            .welcomeEnableNotificationsAction: "Mitteilungen aktivieren",
            .welcomeStepLabel: "Schritt",
            .keychainStatusLabel: "Schlusselbund",
            .securedValue: "Gesichert",
            .pendingValue: "Ausstehend",
            .unlockTitle: "Gesperrt",
            .unlockBody: "Face ID halt dein Schreiben privat, wenn du zuruckkommst.",
            .unlockAction: "Entsperren",
            .restorePhraseAction: "Phrase wiederherstellen",
            .restoreTitle: "Mit 24 Wortern wiederherstellen",
            .restoreBody: "Gib die Phrase lokal ein. Anky sendet sie nie weg.",
            .restorePlaceholder: "24 Worter",
            .restoreConfirmAction: "Wiederherstellen",
            .restoreCancelAction: "Zuruck",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "You",
        ],
        "it": [
            .welcomeIntroBody: "Tutto cio che farai qui e una scusa per scrivere per 8 minuti.",
            .welcomeBiometryBody: "Attiva Face ID per mantenere intatti i tuoi segreti.",
            .welcomeKeychainBody: "Salva la tua frase seed in iCloud Keychain. Apple la protegge per te.",
            .welcomeNotificationsBody: "Attiva le notifiche. Ogni giorno alle 6 AM, Anky ti chiedera: come stai?",
            .welcomeContinueAction: "Continua",
            .welcomeEnableBiometryAction: "Attiva Face ID",
            .welcomeEnableNotificationsAction: "Attiva notifiche",
            .welcomeStepLabel: "Passo",
            .keychainStatusLabel: "Portachiavi",
            .securedValue: "Protetto",
            .pendingValue: "In attesa",
            .unlockTitle: "Bloccato",
            .unlockBody: "Face ID mantiene privata la tua scrittura quando torni.",
            .unlockAction: "Sblocca",
            .restorePhraseAction: "Ripristina frase",
            .restoreTitle: "Ripristina con 24 parole",
            .restoreBody: "Inserisci la frase localmente. Anky non la invia mai.",
            .restorePlaceholder: "24 parole",
            .restoreConfirmAction: "Ripristina",
            .restoreCancelAction: "Indietro",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "Tu",
        ],
        "nl": [
            .welcomeIntroBody: "Alles wat je hier doet is een excuus om 8 minuten te schrijven.",
            .welcomeBiometryBody: "Activeer Face ID om je geheimen intact te houden.",
            .welcomeKeychainBody: "Sla je seed phrase op in iCloud-sleutelhanger. Apple beschermt die voor je.",
            .welcomeNotificationsBody: "Activeer meldingen. Elke dag om 6:00 vraagt Anky: hoe gaat het?",
            .welcomeContinueAction: "Doorgaan",
            .welcomeEnableBiometryAction: "Face ID activeren",
            .welcomeEnableNotificationsAction: "Meldingen activeren",
            .welcomeStepLabel: "Stap",
            .keychainStatusLabel: "Sleutelhanger",
            .securedValue: "Beveiligd",
            .pendingValue: "In afwachting",
            .unlockTitle: "Vergrendeld",
            .unlockBody: "Face ID houdt je schrijven prive wanneer je terugkomt.",
            .unlockAction: "Ontgrendelen",
            .restorePhraseAction: "Herstelzin invoeren",
            .restoreTitle: "Herstellen met 24 woorden",
            .restoreBody: "Voer de zin lokaal in. Anky verstuurt hem nooit.",
            .restorePlaceholder: "24 woorden",
            .restoreConfirmAction: "Herstellen",
            .restoreCancelAction: "Terug",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "Jij",
        ],
        "pl": [
            .welcomeIntroBody: "Wszystko, co tutaj robisz, jest tylko pretekstem do pisania przez 8 minut.",
            .welcomeBiometryBody: "Wlacz Face ID, aby twoje sekrety pozostaly nienaruszone.",
            .welcomeKeychainBody: "Zapisz fraze seed w iCloud Keychain. Apple chroni ja za ciebie.",
            .welcomeNotificationsBody: "Wlacz powiadomienia. Codziennie o 6:00 Anky zapyta: jak sie masz?",
            .welcomeContinueAction: "Kontynuuj",
            .welcomeEnableBiometryAction: "Wlacz Face ID",
            .welcomeEnableNotificationsAction: "Wlacz powiadomienia",
            .welcomeStepLabel: "Krok",
            .keychainStatusLabel: "Pek kluczy",
            .securedValue: "Zabezpieczone",
            .pendingValue: "Oczekuje",
            .unlockTitle: "Zablokowane",
            .unlockBody: "Face ID utrzymuje twoje pisanie w prywatnosci, gdy wracasz.",
            .unlockAction: "Odblokuj",
            .restorePhraseAction: "Przywroc fraze",
            .restoreTitle: "Przywroc z 24 slow",
            .restoreBody: "Wpisz fraze lokalnie. Anky nigdy jej nie wysyla.",
            .restorePlaceholder: "24 slowa",
            .restoreConfirmAction: "Przywroc",
            .restoreCancelAction: "Wroc",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "Ty",
        ],
        "tr": [
            .welcomeIntroBody: "Burada yapacagin her sey 8 dakika yazman icin bir bahane.",
            .welcomeBiometryBody: "Sirrlarini korumak icin Face ID'yi etkinlestir.",
            .welcomeKeychainBody: "Seed ifadenizi iCloud Keychain'e kaydedin. Apple bunu sizin icin korur.",
            .welcomeNotificationsBody: "Bildirimleri ac. Anky her gun sabah 6'da sunu soracak: nasilsin?",
            .welcomeContinueAction: "Devam et",
            .welcomeEnableBiometryAction: "Face ID'yi ac",
            .welcomeEnableNotificationsAction: "Bildirimleri ac",
            .welcomeStepLabel: "Adim",
            .keychainStatusLabel: "Anahtarlik",
            .securedValue: "Korumada",
            .pendingValue: "Beklemede",
            .unlockTitle: "Kilitli",
            .unlockBody: "Geri geldiginde yazini ozel tutan sey Face ID'dir.",
            .unlockAction: "Kilidi ac",
            .restorePhraseAction: "Ifadeyi geri yukle",
            .restoreTitle: "24 kelime ile geri yukle",
            .restoreBody: "Ifadeyi yerel olarak gir. Anky onu asla gondermez.",
            .restorePlaceholder: "24 kelime",
            .restoreConfirmAction: "Geri yukle",
            .restoreCancelAction: "Geri",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "Sen",
        ],
        "ru": [
            .welcomeIntroBody: "Vse, chto ty budesh delat zdes, eto povod pisat 8 minut.",
            .welcomeBiometryBody: "Vklyuchi Face ID, chtoby tvoi sekrety ostalis netronutymi.",
            .welcomeKeychainBody: "Sokhrani seed-frazu v iCloud Keychain. Apple budet berech ee dlya tebya.",
            .welcomeNotificationsBody: "Vklyuchi uvedomleniya. Kazhdyi den v 6:00 Anky sprosit: kak ty?",
            .welcomeContinueAction: "Prodolzhit",
            .welcomeEnableBiometryAction: "Vklyuchit Face ID",
            .welcomeEnableNotificationsAction: "Vklyuchit uvedomleniya",
            .welcomeStepLabel: "Shag",
            .keychainStatusLabel: "Svyazka klyuchei",
            .securedValue: "Zashchishcheno",
            .pendingValue: "V ozhidanii",
            .unlockTitle: "Zablokirovano",
            .unlockBody: "Face ID sokhranyaet tvoyo pis'mo privatnym, kogda ty vozvrashchaeshsya.",
            .unlockAction: "Razblokirovat",
            .restorePhraseAction: "Vosstanovit frazu",
            .restoreTitle: "Vosstanovit po 24 slovam",
            .restoreBody: "Vvedite frazu lokalno. Anky nikuda ee ne otpravlyaet.",
            .restorePlaceholder: "24 slova",
            .restoreConfirmAction: "Vosstanovit",
            .restoreCancelAction: "Nazad",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "You",
        ],
        "ja": [
            .welcomeIntroBody: "ここであなたがすることは、すべて8分書くための口実です。",
            .welcomeBiometryBody: "秘密を守るために Face ID を有効にしてください。",
            .welcomeKeychainBody: "シードフレーズを iCloud Keychain に保存してください。Apple が保護します。",
            .welcomeNotificationsBody: "通知を有効にしてください。毎朝6時に Anky が「元気？」と尋ねます。",
            .welcomeContinueAction: "続ける",
            .welcomeEnableBiometryAction: "Face ID を有効にする",
            .welcomeEnableNotificationsAction: "通知を有効にする",
            .welcomeStepLabel: "ステップ",
            .keychainStatusLabel: "キーチェーン",
            .securedValue: "保護済み",
            .pendingValue: "保留中",
            .unlockTitle: "ロック中",
            .unlockBody: "戻ってきたとき、Face ID があなたの書いたものを私的に保ちます。",
            .unlockAction: "ロック解除",
            .restorePhraseAction: "フレーズを復元",
            .restoreTitle: "24語で復元",
            .restoreBody: "端末上でフレーズを入力してください。Anky は送信しません。",
            .restorePlaceholder: "24語",
            .restoreConfirmAction: "復元",
            .restoreCancelAction: "戻る",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "You",
        ],
        "ko": [
            .welcomeIntroBody: "여기서 하게 될 모든 일은 8분 동안 쓰기 위한 핑계입니다.",
            .welcomeBiometryBody: "비밀을 지키기 위해 Face ID를 활성화하세요.",
            .welcomeKeychainBody: "시드 문구를 iCloud Keychain에 저장하세요. Apple이 보호해 줍니다.",
            .welcomeNotificationsBody: "알림을 활성화하세요. 매일 아침 6시에 Anky가 '어떻게 지내?'라고 묻습니다.",
            .welcomeContinueAction: "계속",
            .welcomeEnableBiometryAction: "Face ID 활성화",
            .welcomeEnableNotificationsAction: "알림 활성화",
            .welcomeStepLabel: "단계",
            .keychainStatusLabel: "키체인",
            .securedValue: "보호됨",
            .pendingValue: "대기 중",
            .unlockTitle: "잠김",
            .unlockBody: "돌아왔을 때 Face ID가 당신의 글을 비공개로 지켜줍니다.",
            .unlockAction: "잠금 해제",
            .restorePhraseAction: "문구 복원",
            .restoreTitle: "24단어로 복원",
            .restoreBody: "문구를 기기에서 입력하세요. Anky 는 보내지 않습니다.",
            .restorePlaceholder: "24단어",
            .restoreConfirmAction: "복원",
            .restoreCancelAction: "뒤로",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "You",
        ],
        "zh": [
            .welcomeIntroBody: "你在这里做的一切，都是为了让你写满 8 分钟。",
            .welcomeBiometryBody: "开启 Face ID，保护你的秘密。",
            .welcomeKeychainBody: "把你的种子短语保存到 iCloud Keychain。Apple 会替你保护它。",
            .welcomeNotificationsBody: "开启通知。每天早上 6 点，Anky 会问你：你好吗？",
            .welcomeContinueAction: "继续",
            .welcomeEnableBiometryAction: "开启 Face ID",
            .welcomeEnableNotificationsAction: "开启通知",
            .welcomeStepLabel: "步骤",
            .keychainStatusLabel: "钥匙串",
            .securedValue: "已保护",
            .pendingValue: "等待中",
            .unlockTitle: "已锁定",
            .unlockBody: "当你回来时，Face ID 会让你的文字保持私密。",
            .unlockAction: "解锁",
            .restorePhraseAction: "恢复短语",
            .restoreTitle: "用24个词恢复",
            .restoreBody: "请在本地输入短语。Anky 不会发送它。",
            .restorePlaceholder: "24个词",
            .restoreConfirmAction: "恢复",
            .restoreCancelAction: "返回",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "You",
        ],
        "ar": [
            .welcomeIntroBody: "كل ما ستفعله هنا هو عذر لكي تكتب لمدة 8 دقائق.",
            .welcomeBiometryBody: "فعّل Face ID ليبقى ما تكتبه سرا.",
            .welcomeKeychainBody: "احفظ عبارة البذرة في iCloud Keychain. Apple ستحميها لك.",
            .welcomeNotificationsBody: "فعّل الاشعارات. كل يوم عند السادسة صباحا، ستسألك Anky: كيف حالك؟",
            .welcomeContinueAction: "متابعة",
            .welcomeEnableBiometryAction: "تفعيل Face ID",
            .welcomeEnableNotificationsAction: "تفعيل الاشعارات",
            .welcomeStepLabel: "خطوة",
            .keychainStatusLabel: "سلسلة المفاتيح",
            .securedValue: "محمي",
            .pendingValue: "قيد الانتظار",
            .unlockTitle: "مقفل",
            .unlockBody: "Face ID يبقي كتابتك خاصة عندما تعود.",
            .unlockAction: "فتح القفل",
            .restorePhraseAction: "استعادة العبارة",
            .restoreTitle: "استعادة ب 24 كلمة",
            .restoreBody: "ادخل العبارة محليا. Anky لا ترسلها الى اي مكان.",
            .restorePlaceholder: "24 كلمة",
            .restoreConfirmAction: "استعادة",
            .restoreCancelAction: "رجوع",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "You",
        ],
        "hi": [
            .welcomeIntroBody: "तुम यहां जो कुछ भी करोगे, वह 8 मिनट लिखने का एक बहाना है।",
            .welcomeBiometryBody: "अपने राज सुरक्षित रखने के लिए Face ID चालू करें।",
            .welcomeKeychainBody: "अपनी seed phrase को iCloud Keychain में सहेजें। Apple इसे आपके लिए सुरक्षित रखेगा।",
            .welcomeNotificationsBody: "नोटिफिकेशन चालू करें। हर दिन सुबह 6 बजे, Anky पूछेगा: आप कैसे हैं?",
            .welcomeContinueAction: "जारी रखें",
            .welcomeEnableBiometryAction: "Face ID चालू करें",
            .welcomeEnableNotificationsAction: "नोटिफिकेशन चालू करें",
            .welcomeStepLabel: "चरण",
            .keychainStatusLabel: "कीचेन",
            .securedValue: "सुरक्षित",
            .pendingValue: "प्रतीक्षा में",
            .unlockTitle: "लॉक्ड",
            .unlockBody: "जब आप लौटते हैं, Face ID आपकी लिखाई को निजी रखता है।",
            .unlockAction: "अनलॉक",
            .restorePhraseAction: "वाक्यांश बहाल करें",
            .restoreTitle: "24 शब्दों से बहाल करें",
            .restoreBody: "वाक्यांश यहीं दर्ज करें। Anky इसे कहीं नहीं भेजता।",
            .restorePlaceholder: "24 शब्द",
            .restoreConfirmAction: "बहाल करें",
            .restoreCancelAction: "वापस",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "You",
        ],
        "id": [
            .welcomeIntroBody: "Semua yang kamu lakukan di sini hanyalah alasan untuk menulis selama 8 menit.",
            .welcomeBiometryBody: "Aktifkan Face ID untuk menjaga rahasiamu tetap utuh.",
            .welcomeKeychainBody: "Simpan seed phrase-mu di iCloud Keychain. Apple akan menjaganya untukmu.",
            .welcomeNotificationsBody: "Aktifkan notifikasi. Setiap hari pukul 6 pagi, Anky akan bertanya: apa kabar?",
            .welcomeContinueAction: "Lanjutkan",
            .welcomeEnableBiometryAction: "Aktifkan Face ID",
            .welcomeEnableNotificationsAction: "Aktifkan notifikasi",
            .welcomeStepLabel: "Langkah",
            .keychainStatusLabel: "Keychain",
            .securedValue: "Aman",
            .pendingValue: "Tertunda",
            .unlockTitle: "Terkunci",
            .unlockBody: "Face ID menjaga tulisanmu tetap pribadi saat kamu kembali.",
            .unlockAction: "Buka",
            .restorePhraseAction: "Pulihkan frasa",
            .restoreTitle: "Pulihkan dengan 24 kata",
            .restoreBody: "Masukkan frasa secara lokal. Anky tidak pernah mengirimkannya.",
            .restorePlaceholder: "24 kata",
            .restoreConfirmAction: "Pulihkan",
            .restoreCancelAction: "Kembali",
            .storiesTab: "Stories",
            .writeTab: "Write",
            .youTab: "Kamu",
        ],
    ]
}
