//
//  WritingExperienceStrings.swift
//  Anky
//

import Foundation

enum WritingCopyKey: String {
    case writeNow
    case eightMinutes
    case continueAction
    case tryAgainAction
    case resumeHint
    case wordsLabel
    case livesLabel
    case ankyListeningTitle
    case ankyListeningBody
    case ankyBornTitle
    case ankyBornBody
    case writingSafeTitle
    case writingSafeBody
    case openSitAction
    case writeAgainAction
    case reflectionLabel
    case chatAction
    case shareAction
    case replyAction
    case submitAnkyAction
}

struct WritingExperienceStrings {
    private static let fallbackLanguageCode = "en"

    static var current: WritingExperienceStrings {
        WritingExperienceStrings(languageCode: resolvedLanguageCode())
    }

    let languageCode: String

    subscript(key: WritingCopyKey) -> String {
        if let translation = Self.translations[languageCode]?[key] {
            return translation
        }

        return Self.translations[Self.fallbackLanguageCode]?[key] ?? key.rawValue
    }

    private static func resolvedLanguageCode() -> String {
        let preferred = Locale.preferredLanguages.first ?? fallbackLanguageCode
        let normalized = preferred.replacingOccurrences(of: "_", with: "-")
        return normalized.split(separator: "-").first.map(String.init) ?? fallbackLanguageCode
    }

    private static let translations: [String: [WritingCopyKey: String]] = [
        "en": [
            .writeNow: "Write now",
            .eightMinutes: "8 minutes",
            .continueAction: "Continue",
            .tryAgainAction: "try again",
            .resumeHint: "Type to resume. (1 life left)",
            .wordsLabel: "words",
            .livesLabel: "lives",
            .ankyListeningTitle: "An anky is forming.",
            .ankyListeningBody: "The writing is already safe. I am sending the real anky now.",
            .ankyBornTitle: "An anky was born.",
            .ankyBornBody: "The page held long enough. Sit with what it opened.",
            .writingSafeTitle: "The writing is safe locally.",
            .writingSafeBody: "It will sync when the backend is ready again.",
            .openSitAction: "Open Sit",
            .writeAgainAction: "Write again",
            .reflectionLabel: "Reflection",
            .chatAction: "Chat",
            .shareAction: "Share",
            .replyAction: "Reply",
            .submitAnkyAction: "Submit my anky",
        ],
        "es": [
            .writeNow: "Escribe ahora",
            .eightMinutes: "8 minutos",
            .continueAction: "Continuar",
            .tryAgainAction: "intentar de nuevo",
            .resumeHint: "Escribe para seguir. (queda 1 vida)",
            .wordsLabel: "palabras",
            .livesLabel: "vidas",
            .ankyListeningTitle: "Se esta formando un anky.",
            .ankyListeningBody: "La escritura ya esta a salvo. Estoy enviando el anky real ahora.",
            .ankyBornTitle: "Nacio un anky.",
            .ankyBornBody: "La pagina aguanto lo suficiente. Sientate con lo que se abrio.",
            .writingSafeTitle: "La escritura esta segura en este dispositivo.",
            .writingSafeBody: "Se sincronizara cuando el backend vuelva a estar listo.",
            .openSitAction: "Abrir Sit",
            .writeAgainAction: "Escribir de nuevo",
            .reflectionLabel: "Reflexion",
            .chatAction: "Chat",
            .shareAction: "Compartir",
            .replyAction: "Responder",
            .submitAnkyAction: "Enviar mi anky",
        ],
        "pt": [
            .writeNow: "Escreva agora",
            .eightMinutes: "8 minutos",
            .continueAction: "Continuar",
            .tryAgainAction: "tentar de novo",
            .resumeHint: "Digite para retomar. (1 vida restante)",
            .wordsLabel: "palavras",
            .livesLabel: "vidas",
            .ankyListeningTitle: "Um anky esta se formando.",
            .ankyListeningBody: "A escrita ja esta segura. Estou enviando o anky real agora.",
            .ankyBornTitle: "Um anky nasceu.",
            .ankyBornBody: "A pagina sustentou o suficiente. Fique com o que se abriu.",
            .writingSafeTitle: "A escrita esta segura neste aparelho.",
            .writingSafeBody: "Ela vai sincronizar quando o backend estiver pronto outra vez.",
            .openSitAction: "Abrir Sit",
            .writeAgainAction: "Escrever de novo",
            .reflectionLabel: "Reflexao",
            .chatAction: "Chat",
            .shareAction: "Compartilhar",
            .replyAction: "Responder",
            .submitAnkyAction: "Enviar meu anky",
        ],
        "fr": [
            .writeNow: "Ecris maintenant",
            .eightMinutes: "8 minutes",
            .continueAction: "Continuer",
            .tryAgainAction: "reessayer",
            .resumeHint: "Tapez pour reprendre. (1 vie restante)",
            .wordsLabel: "mots",
            .livesLabel: "vies",
            .ankyListeningTitle: "Un anky est en train de naitre.",
            .ankyListeningBody: "Le texte est deja en securite. J'envoie le vrai anky maintenant.",
            .ankyBornTitle: "Un anky est ne.",
            .ankyBornBody: "La page a tenu assez longtemps. Reste avec ce qui s'est ouvert.",
            .writingSafeTitle: "Le texte est en securite sur cet appareil.",
            .writingSafeBody: "Il se synchronisera quand le backend sera de nouveau pret.",
            .openSitAction: "Ouvrir Sit",
            .writeAgainAction: "Ecrire encore",
            .reflectionLabel: "Reflexion",
            .chatAction: "Chat",
            .shareAction: "Partager",
            .replyAction: "Repondre",
            .submitAnkyAction: "Envoyer mon anky",
        ],
        "de": [
            .writeNow: "Schreib jetzt",
            .eightMinutes: "8 Minuten",
            .continueAction: "Weiter",
            .tryAgainAction: "noch einmal",
            .resumeHint: "Schreibe, um fortzusetzen. (1 Leben ubrig)",
            .wordsLabel: "Worter",
            .livesLabel: "Leben",
            .ankyListeningTitle: "Ein Anky entsteht.",
            .ankyListeningBody: "Der Text ist bereits sicher. Ich sende jetzt das echte Anky.",
            .ankyBornTitle: "Ein Anky wurde geboren.",
            .ankyBornBody: "Die Seite hat lange genug gehalten. Bleib bei dem, was sich geoffnet hat.",
            .writingSafeTitle: "Der Text ist lokal gesichert.",
            .writingSafeBody: "Er wird synchronisiert, sobald das Backend wieder bereit ist.",
            .openSitAction: "Sit offnen",
            .writeAgainAction: "Noch einmal schreiben",
            .reflectionLabel: "Reflexion",
            .chatAction: "Chat",
            .shareAction: "Teilen",
            .replyAction: "Antworten",
            .submitAnkyAction: "Mein Anky senden",
        ],
        "it": [
            .writeNow: "Scrivi ora",
            .eightMinutes: "8 minuti",
            .continueAction: "Continua",
            .tryAgainAction: "riprova",
            .resumeHint: "Scrivi per riprendere. (1 vita rimasta)",
            .wordsLabel: "parole",
            .livesLabel: "vite",
            .ankyListeningTitle: "Si sta formando un anky.",
            .ankyListeningBody: "La scrittura e gia al sicuro. Sto inviando ora il vero anky.",
            .ankyBornTitle: "E nato un anky.",
            .ankyBornBody: "La pagina ha retto abbastanza a lungo. Resta con quello che si e aperto.",
            .writingSafeTitle: "La scrittura e al sicuro sul dispositivo.",
            .writingSafeBody: "Si sincronizzera quando il backend sara di nuovo pronto.",
            .openSitAction: "Apri Sit",
            .writeAgainAction: "Scrivi di nuovo",
            .reflectionLabel: "Riflessione",
            .chatAction: "Chat",
            .shareAction: "Condividi",
            .replyAction: "Rispondi",
            .submitAnkyAction: "Invia il mio anky",
        ],
        "nl": [
            .writeNow: "Schrijf nu",
            .eightMinutes: "8 minuten",
            .continueAction: "Doorgaan",
            .tryAgainAction: "opnieuw proberen",
            .resumeHint: "Typ om verder te gaan. (nog 1 leven)",
            .wordsLabel: "woorden",
            .livesLabel: "levens",
            .ankyListeningTitle: "Er vormt zich een anky.",
            .ankyListeningBody: "Het schrijven is al veilig. Ik stuur nu de echte anky.",
            .ankyBornTitle: "Er is een anky geboren.",
            .ankyBornBody: "De pagina hield lang genoeg stand. Blijf bij wat er open ging.",
            .writingSafeTitle: "Het schrijven staat veilig op dit toestel.",
            .writingSafeBody: "Het synchroniseert zodra de backend weer klaar is.",
            .openSitAction: "Open Sit",
            .writeAgainAction: "Opnieuw schrijven",
            .reflectionLabel: "Reflectie",
            .chatAction: "Chat",
            .shareAction: "Delen",
            .replyAction: "Antwoorden",
            .submitAnkyAction: "Mijn anky verzenden",
        ],
        "pl": [
            .writeNow: "Pisz teraz",
            .eightMinutes: "8 minut",
            .continueAction: "Kontynuuj",
            .tryAgainAction: "sprobuj ponownie",
            .resumeHint: "Pisz dalej. (zostalo 1 zycie)",
            .wordsLabel: "slowa",
            .livesLabel: "zycia",
            .ankyListeningTitle: "Powstaje anky.",
            .ankyListeningBody: "Pisanie jest juz bezpieczne. Wysylam teraz prawdziwe anky.",
            .ankyBornTitle: "Narodzilo sie anky.",
            .ankyBornBody: "Strona wytrzymala wystarczajaco dlugo. Zostan przy tym, co sie otworzylo.",
            .writingSafeTitle: "Pisanie jest zapisane lokalnie.",
            .writingSafeBody: "Zsynchronizuje sie, gdy backend znow bedzie gotowy.",
            .openSitAction: "Otworz Sit",
            .writeAgainAction: "Pisz ponownie",
            .reflectionLabel: "Refleksja",
            .chatAction: "Czat",
            .shareAction: "Udostepnij",
            .replyAction: "Odpowiedz",
            .submitAnkyAction: "Wyslij moje anky",
        ],
        "tr": [
            .writeNow: "Simdi yaz",
            .eightMinutes: "8 dakika",
            .continueAction: "Devam et",
            .tryAgainAction: "yeniden dene",
            .resumeHint: "Surdurmek icin yaz. (1 can kaldi)",
            .wordsLabel: "kelime",
            .livesLabel: "can",
            .ankyListeningTitle: "Bir anky olusuyor.",
            .ankyListeningBody: "Yazi zaten guvende. Gercek anky'yi simdi gonderiyorum.",
            .ankyBornTitle: "Bir anky dogdu.",
            .ankyBornBody: "Sayfa yeterince uzun tuttu. Acilan sey ile kal.",
            .writingSafeTitle: "Yazi cihazda guvende.",
            .writingSafeBody: "Backend yeniden hazir oldugunda senkronize olacak.",
            .openSitAction: "Sit'i ac",
            .writeAgainAction: "Yeniden yaz",
            .reflectionLabel: "Yansima",
            .chatAction: "Sohbet",
            .shareAction: "Paylas",
            .replyAction: "Yanitla",
            .submitAnkyAction: "Anky'mi gonder",
        ],
        "ru": [
            .writeNow: "Pishi seichas",
            .eightMinutes: "8 minut",
            .continueAction: "Prodolzhit",
            .tryAgainAction: "poprobovat snova",
            .resumeHint: "Pechatai, chtoby vozobnovit. (ostalas 1 zhizn)",
            .wordsLabel: "slov",
            .livesLabel: "zhizni",
            .ankyListeningTitle: "Anky rozhdaetsya.",
            .ankyListeningBody: "Tekst uzhe v bezopasnosti. Ya otpravlyayu nastoyashchii anky.",
            .ankyBornTitle: "Anky rodilsya.",
            .ankyBornBody: "Stranitsa vydershala dostatochno dolgo. Pobud s tem, chto otkrylos.",
            .writingSafeTitle: "Tekst sokhranen lokalno.",
            .writingSafeBody: "On sinkhroniziruetsya, kogda backend snova budet gotov.",
            .openSitAction: "Otkryt Sit",
            .writeAgainAction: "Pisati snova",
            .reflectionLabel: "Refleksiya",
            .chatAction: "Chat",
            .shareAction: "Podelitsya",
            .replyAction: "Otvetit",
            .submitAnkyAction: "Otpravit moi anky",
        ],
        "ja": [
            .writeNow: "今すぐ書く",
            .eightMinutes: "8分",
            .continueAction: "続ける",
            .tryAgainAction: "もう一度",
            .resumeHint: "入力して再開してください。（残り1ライフ）",
            .wordsLabel: "語",
            .livesLabel: "ライフ",
            .ankyListeningTitle: "Anky が形になっています。",
            .ankyListeningBody: "書いた内容はもう安全です。今、本当の anky を送っています。",
            .ankyBornTitle: "Anky が生まれました。",
            .ankyBornBody: "ページは十分に持ちこたえました。開いたものと一緒にいてください。",
            .writingSafeTitle: "書いた内容はこの端末に安全に残っています。",
            .writingSafeBody: "バックエンドの準備が戻れば同期されます。",
            .openSitAction: "Sit を開く",
            .writeAgainAction: "もう一度書く",
            .reflectionLabel: "リフレクション",
            .chatAction: "チャット",
            .shareAction: "共有",
            .replyAction: "返信",
            .submitAnkyAction: "anky を送信",
        ],
        "ko": [
            .writeNow: "지금 쓰기",
            .eightMinutes: "8분",
            .continueAction: "계속",
            .tryAgainAction: "다시 시도",
            .resumeHint: "입력해서 이어가세요. (생명 1개 남음)",
            .wordsLabel: "단어",
            .livesLabel: "생명",
            .ankyListeningTitle: "anky가 형성되고 있습니다.",
            .ankyListeningBody: "글은 이미 안전합니다. 지금 진짜 anky를 보내고 있습니다.",
            .ankyBornTitle: "anky가 태어났습니다.",
            .ankyBornBody: "페이지가 충분히 버텼습니다. 열린 것을 그대로 느껴보세요.",
            .writingSafeTitle: "글은 이 기기에 안전하게 남아 있습니다.",
            .writingSafeBody: "백엔드가 다시 준비되면 동기화됩니다.",
            .openSitAction: "Sit 열기",
            .writeAgainAction: "다시 쓰기",
            .reflectionLabel: "리플렉션",
            .chatAction: "채팅",
            .shareAction: "공유",
            .replyAction: "답장",
            .submitAnkyAction: "내 anky 보내기",
        ],
        "zh": [
            .writeNow: "现在写",
            .eightMinutes: "8 分钟",
            .continueAction: "继续",
            .tryAgainAction: "再试一次",
            .resumeHint: "直接输入继续。 (还剩 1 条命)",
            .wordsLabel: "字词",
            .livesLabel: "生命",
            .ankyListeningTitle: "一个 anky 正在形成。",
            .ankyListeningBody: "文字已经安全保存。现在正在发送真正的 anky。",
            .ankyBornTitle: "一个 anky 诞生了。",
            .ankyBornBody: "这一页撑得够久了。和打开的东西待在一起。",
            .writingSafeTitle: "文字已安全保存在本机。",
            .writingSafeBody: "当后端重新可用时，它会同步。",
            .openSitAction: "打开 Sit",
            .writeAgainAction: "再写一次",
            .reflectionLabel: "反思",
            .chatAction: "聊天",
            .shareAction: "分享",
            .replyAction: "回复",
            .submitAnkyAction: "提交我的 anky",
        ],
        "ar": [
            .writeNow: "اكتب الآن",
            .eightMinutes: "8 دقائق",
            .continueAction: "متابعة",
            .tryAgainAction: "حاول مرة اخرى",
            .resumeHint: "اكتب للمتابعة. (تبقت محاولة واحدة)",
            .wordsLabel: "كلمات",
            .livesLabel: "محاولات",
            .ankyListeningTitle: "يولد anky الان.",
            .ankyListeningBody: "الكتابة محفوظة بالفعل. يتم ارسال anky الحقيقي الان.",
            .ankyBornTitle: "ولد anky.",
            .ankyBornBody: "صمدت الصفحة بما يكفي. ابق مع ما انفتح.",
            .writingSafeTitle: "الكتابة محفوظة محليا.",
            .writingSafeBody: "ستتم المزامنة عندما يصبح الخادم جاهزا من جديد.",
            .openSitAction: "افتح Sit",
            .writeAgainAction: "اكتب من جديد",
            .reflectionLabel: "تامل",
            .chatAction: "دردشة",
            .shareAction: "مشاركة",
            .replyAction: "رد",
            .submitAnkyAction: "ارسل anky الخاص بي",
        ],
        "hi": [
            .writeNow: "अभी लिखो",
            .eightMinutes: "8 मिनट",
            .continueAction: "जारी रखें",
            .tryAgainAction: "फिर से कोशिश करें",
            .resumeHint: "फिर शुरू करने के लिए टाइप करें। (1 जीवन बाकी)",
            .wordsLabel: "शब्द",
            .livesLabel: "जीवन",
            .ankyListeningTitle: "एक anky बन रहा है।",
            .ankyListeningBody: "लिखाई पहले से सुरक्षित है। मैं अभी असली anky भेज रहा हूं।",
            .ankyBornTitle: "एक anky जन्मा।",
            .ankyBornBody: "पन्ना काफी देर तक टिक गया। जो खुला है उसके साथ रहो।",
            .writingSafeTitle: "लिखाई इस डिवाइस पर सुरक्षित है।",
            .writingSafeBody: "बैकएंड फिर तैयार होते ही यह सिंक हो जाएगी।",
            .openSitAction: "Sit खोलें",
            .writeAgainAction: "फिर से लिखो",
            .reflectionLabel: "चिंतन",
            .chatAction: "चैट",
            .shareAction: "साझा करें",
            .replyAction: "उत्तर",
            .submitAnkyAction: "Mera anky bhejo",
        ],
        "id": [
            .writeNow: "Tulis sekarang",
            .eightMinutes: "8 menit",
            .continueAction: "Lanjutkan",
            .tryAgainAction: "coba lagi",
            .resumeHint: "Ketik untuk meneruskan. (tersisa 1 nyawa)",
            .wordsLabel: "kata",
            .livesLabel: "nyawa",
            .ankyListeningTitle: "Sebuah anky sedang terbentuk.",
            .ankyListeningBody: "Tulisan ini sudah aman. Aku sedang mengirim anky yang sebenarnya sekarang.",
            .ankyBornTitle: "Sebuah anky lahir.",
            .ankyBornBody: "Halaman ini bertahan cukup lama. Tinggallah bersama yang terbuka.",
            .writingSafeTitle: "Tulisan ini aman di perangkat.",
            .writingSafeBody: "Tulisan ini akan sinkron saat backend siap lagi.",
            .openSitAction: "Buka Sit",
            .writeAgainAction: "Tulis lagi",
            .reflectionLabel: "Refleksi",
            .chatAction: "Chat",
            .shareAction: "Bagikan",
            .replyAction: "Balas",
            .submitAnkyAction: "Kirim anky saya",
        ],
    ]
}
